# Patient Admissions and Billing Analysis

##### Import Essential Libraries

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

##### Load Unprocessed Data

In [2]:
df = pd.read_csv("../../Dataset/Raw/healthcare_dataset.csv")

##### Summary Statistics & Distribution Overview

In [3]:
df.shape

(55500, 15)

In [4]:
df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  str
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  str
 3   Blood Type          55500 non-null  str
 4   Medical Condition   55500 non-null  str
 5   Date of Admission   55500 non-null  str
 6   Doctor              55500 non-null  str
 7   Hospital            55500 non-null  str
 8   Insurance Provider  55500 non-null  str
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  str
 13  Medication          55500 non-null  str
 14  Test Results        55500 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 12.3 MB

In [6]:
df.head(10)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
5,EMILY JOHNSOn,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.110951,389,Urgent,2023-12-24,Ibuprofen,Normal
6,edwArD EDWaRDs,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.872345,389,Emergency,2020-11-15,Paracetamol,Inconclusive
7,CHrisTInA MARtinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,"Powell Robinson and Valdez,",Cigna,45820.462722,277,Emergency,2022-01-07,Paracetamol,Inconclusive
8,JASmINe aGuIlaR,82,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich and,Cigna,50119.222792,316,Elective,2020-07-14,Aspirin,Abnormal
9,ChRISTopher BerG,58,Female,AB-,Cancer,2021-05-23,Heather Day,Padilla-Walker,UnitedHealthcare,19784.631062,249,Elective,2021-06-22,Paracetamol,Inconclusive

### Data Cleaning & Preprocessing

##### Check Missing Or Null Values

In [7]:
missing_values = df.isnull().sum()  

print("Missing values in each column:",)
print(missing_values)

total_missing = df.isnull().sum().sum()
if total_missing == 0:
    print("No missing values found. No cleaning required.")
else:
    print("Missing values found. Investigate before cleaning.")

Missing values in each column:
Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64
No missing values found. No cleaning required.

##### Standardize Column Names (snake_case)

In [8]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df = df.rename(columns={"date_of_admission": "admission_date"})
print(list(df.columns))

['name', 'age', 'gender', 'blood_type', 'medical_condition', 'admission_date', 'doctor', 'hospital', 'insurance_provider', 'billing_amount', 'room_number', 'admission_type', 'discharge_date', 'medication', 'test_results']

##### Identify Date Columns

In [9]:
# Check the data type of every column
print("Current column data types:")
print(df.dtypes)

Current column data types:
name                      str
age                     int64
gender                    str
blood_type                str
medical_condition         str
admission_date            str
doctor                    str
hospital                  str
insurance_provider        str
billing_amount        float64
room_number             int64
admission_type            str
discharge_date            str
medication                str
test_results              str
dtype: object

##### Cast Date Columns to Datetime

In [10]:
# Convert admission dates to datetime
df["admission_date"]  = pd.to_datetime(
    df["admission_date"] 
)

# Convert discharge dates to datetime
df["discharge_date"] = pd.to_datetime(
    df["discharge_date"]
)

##### Validate Updated Dtypes

In [11]:

print("Admission date type:", df["admission_date"].dtype)

print("\nDischarge date type:", df["discharge_date"].dtype)

Admission date type: datetime64[us]

Discharge date type: datetime64[us]

##### Check & View Duplicate Records

In [12]:
duplicate_count = df.duplicated().sum()
print("Exact duplicate rows:", duplicate_count)

duplicate_rows = df[df.duplicated()]
duplicate_rows.head(10)

Exact duplicate rows: 534

,name,age,gender,blood_type,medical_condition,admission_date,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
50023,Samuel joYCe,56,Male,O+,Arthritis,2022-11-03,Krista Hartman,Thomas-Ballard,UnitedHealthcare,15654.830587,157,Urgent,2022-11-22,Aspirin,Inconclusive
50040,KIMBErly vasqueZ,26,Male,A-,Obesity,2023-10-23,Jennifer Bennett,Cowan Inc,UnitedHealthcare,38142.109678,313,Urgent,2023-11-18,Penicillin,Abnormal
50055,SCoTT tHOrNton,55,Female,B-,Obesity,2021-04-08,Joshua Ingram,Keller LLC,Medicare,30894.904511,455,Urgent,2021-04-15,Aspirin,Abnormal
50070,wiLliam LEe,27,Female,O+,Arthritis,2020-01-31,Lauren Montgomery,Winters-Simon,Cigna,46229.434901,153,Elective,2020-02-13,Lipitor,Normal
50078,chRistOPheR NoRrIs,38,Male,AB-,Arthritis,2023-01-14,Denise Blair,Inc Morales,Medicare,9072.127142,452,Emergency,2023-02-12,Penicillin,Normal
50081,TRAVis best,65,Female,B+,Asthma,2020-01-15,Kristin Anderson,Thomas-Johnson,Blue Cross,5903.933834,246,Urgent,2020-02-14,Aspirin,Abnormal
50086,MATTHEw foSTer,60,Female,AB-,Obesity,2020-02-12,Taylor Frank,Ltd Alvarado,Aetna,4735.300151,140,Urgent,2020-02-25,Penicillin,Normal
50090,MAnuEL THOrntON,51,Male,O-,Asthma,2023-07-25,Kathy King,"Morgan Hernandez, and Beck",UnitedHealthcare,45601.814762,378,Urgent,2023-08-08,Ibuprofen,Normal
50095,MadelINe BAKer,49,Male,A+,Cancer,2019-11-18,Melissa Alvarado,"Lane Riley and Fisher,",Cigna,3840.740363,144,Emergency,2019-12-07,Paracetamol,Inconclusive
50102,ReginAld WRight,50,Male,AB-,Asthma,2020-04-25,Michael Arias,"Clark, and Estes Thomas",Aetna,26886.655207,210,Urgent,2020-05-03,Paracetamol,Abnormal

##### Drop Duplicate Records

In [13]:
# Save the original row count for comparison
rows_before = len(df)

# Remove exact duplicate rows
df = df.drop_duplicates()

# Count rows after cleaning
rows_after = len(df)

print("Rows removed:", rows_before - rows_after,"\nRemaining duplicates:", df.duplicated().sum())

Rows removed: 534
Remaining duplicates: 0

##### Identify Inconsistent Text Values

In [14]:
# Check text columns
text_columns = df.select_dtypes(include=["object", "str"]).columns
print(f"Text columns:\n{text_columns.tolist()}")

# Inspect examples of patient names
print(f"\nFirst 10 patient names:\n{df["name"].head(10).to_list()}")

# Count unique values in important categories
category_columns = [
    "gender",
    "blood_type",
    "medical_condition",
    "admission_type",
    "insurance_provider",
    "medication",
    "test_results"
]

for column in category_columns:
    print(f"\n{column}:{sorted(df[column].dropna().astype(str).unique())}")

Text columns:
['name', 'gender', 'blood_type', 'medical_condition', 'doctor', 'hospital', 'insurance_provider', 'admission_type', 'medication', 'test_results']

First 10 patient names:
['Bobby JacksOn', 'LesLie TErRy', 'DaNnY sMitH', 'andrEw waTtS', 'adrIENNE bEll', 'EMILY JOHNSOn', 'edwArD EDWaRDs', 'CHrisTInA MARtinez', 'JASmINe aGuIlaR', 'ChRISTopher BerG']

gender:['Female', 'Male']

blood_type:['A+', 'A-', 'AB+', 'AB-', 'B+', 'B-', 'O+', 'O-']

medical_condition:['Arthritis', 'Asthma', 'Cancer', 'Diabetes', 'Hypertension', 'Obesity']

admission_type:['Elective', 'Emergency', 'Urgent']

insurance_provider:['Aetna', 'Blue Cross', 'Cigna', 'Medicare', 'UnitedHealthcare']

medication:['Aspirin', 'Ibuprofen', 'Lipitor', 'Paracetamol', 'Penicillin']

test_results:['Abnormal', 'Inconclusive', 'Normal']

##### Standardize Categorical Values

In [15]:
# Remove spaces if exist at the beginning and end of text values
for column in text_columns:
    df[column] = df[column].str.strip()

# Standardize capitalization in selected categories
columns =  [
    "name",
    "gender",
    "blood_type",
    "medical_condition",
    "admission_type",
    "insurance_provider",
    "medication",
    "test_results"
]
for col in columns:
    df[col] = df[col].str.title()

##### Identify Inconsistent Age Values

In [16]:
# Find missing age values
age_data = (df["age"].isnull().sum())
invalid_age = ((df["age"] < 0) | (df["age"] > 120)).sum()
print("Missing ages:",age_data,
      "\nMinimum age:", df["age"].min(),
      "\nMaximum age:", df["age"].max(),
      "\nAges outside screening range:", invalid_age)

Missing ages: 0
Minimum age: 13
Maximum age: 89
Ages outside screening range: 0

##### Identify Inconsistent Billing Amount

In [17]:
# Review basic billing statistics
print(f"Billing Amount summary:\n{df["billing_amount"].describe()}")

# Count missing billing values
print(f"\nMissing billing values:{df["billing_amount"].isnull().sum()}")

# Count zero and negative bills
print(f"\nZero bills:{(df["billing_amount"] == 0).sum()}")
print(f"\nNegative bills:{(df["billing_amount"] < 0).sum()}")

Billing Amount summary:
count    54966.000000
mean     25544.306284
std      14208.409711
min      -2008.492140
25%      13243.718641
50%      25542.749145
75%      37819.858159
max      52764.276736
Name: billing_amount, dtype: float64

Missing billing values:0

Zero bills:0

Negative bills:106

##### Standardize Billing Amounts

In [18]:
# Create a column as a flag for zero or negative bills
df["billing_review_needed"] = df["billing_amount"] <= 0

# Count records requiring review
print("Bills requiring review:", df["billing_review_needed"].sum())

# Display flagged records
display(df.loc[df["billing_review_needed"], ["hospital", "medical_condition", "billing_amount"]].head(10))

df.shape

Bills requiring review: 106

                          hospital medical_condition  billing_amount
132      and Johnson Moore, Branch            Cancer     -502.507813
799                  Hunter-Hughes            Asthma    -1018.245371
1018         and Wagner, Lee Klein      Hypertension     -306.364925
1421                  Group Peters            Asthma     -109.097122
2103       and Huff Reeves, Dennis          Diabetes     -576.727907
2696                     James Ltd          Diabetes     -135.986000
2855  Carter Carter, and Patterson      Hypertension     -370.983674
3772                   Johnson Inc           Obesity    -1310.272895
5445        Bowen Lopez, and Terry         Arthritis     -692.408820
5708                      Inc Ward          Diabetes     -353.865186

(54966, 16)

### Export Processed Dataset

In [19]:
# Create the Cleaned folder if it does not exist
cleaned_dir = Path("../../Dataset/Cleaned")
cleaned_dir.mkdir(parents=True, exist_ok=True)

# Export cleaned data to CSV
output_path = cleaned_dir / "cleaned_healthcare_data.csv"
df.to_csv(output_path, index=False)

print(f"File successfully saved to: {output_path.resolve()}")

File successfully saved to: C:\Users\LOQ\OneDrive\Desktop\Data Analytics projects\p2 healthcare domain\Dataset\Cleaned\cleaned_healthcare_data.csv

### Read Cleaned Dataset

In [20]:
file_path = Path("../../Dataset/Cleaned/cleaned_healthcare_data.csv")

if file_path.exists():
    df = pd.read_csv(file_path, parse_dates=["admission_date", "discharge_date"])
else:
    print("Cleaned CSV not found. Check the file path.")

### Essential Exploratory Data Analysis (EDA)

##### Task 1: Generate Summary Statistics

In [21]:
# 1. Check the number of rows and columns
print("Dataset shape:", df.shape)

# 2. Summary of numerical columns
display(df[["age", "billing_amount"]].describe())

# 3. Summary of categorical columns
display(df[["gender", "medical_condition", "admission_type"]].describe())

Dataset shape: (54966, 16)

                age  billing_amount
count  54966.000000    54966.000000
mean      51.535185    25544.306284
std       19.605661    14208.409711
min       13.000000    -2008.492140
25%       35.000000    13243.718641
50%       52.000000    25542.749145
75%       68.000000    37819.858159
max       89.000000    52764.276736

       gender medical_condition admission_type
count   54966             54966          54966
unique      2                 6              3
top      Male         Arthritis       Elective
freq    27496              9218          18473

##### Task 2: Analyze Common Medical Conditions & Admission Types

In [22]:
# 1. Count patients by medical condition
print("Medical Conditions:")
display(df["medical_condition"].value_counts())

# 2. Count patients by admission type
print("\nAdmission Types:")
display(df["admission_type"].value_counts())

Medical Conditions:

medical_condition
Arthritis       9218
Diabetes        9216
Hypertension    9151
Obesity         9146
Cancer          9140
Asthma          9095
Name: count, dtype: int64

Admission Types:

admission_type
Elective     18473
Urgent       18391
Emergency    18102
Name: count, dtype: int64

### Essential Business Questions

##### Question 1: Calculate the average billing amount by medical condition

In [23]:
billing_by_condition = (
    df.groupby("medical_condition")["billing_amount"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

display(billing_by_condition)

medical_condition
Obesity         25804.36
Diabetes        25660.48
Asthma          25633.46
Arthritis       25511.78
Hypertension    25503.06
Cancer          25152.32
Name: billing_amount, dtype: float64

##### Question2: Which admission type has the highest average billing amount?

In [24]:
billing_by_admission = (
    df.groupby("admission_type")["billing_amount"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

display(billing_by_admission)

admission_type
Elective     25612.14
Urgent       25514.53
Emergency    25505.33
Name: billing_amount, dtype: float64

##### Question3: How many records belong to each admission type, and what percentage of the dataset does each type represent?

In [25]:
# Count records by admission type
admission_counts = df["admission_type"].value_counts()

# Calculate percentage for each admission type
admission_percentages = (
    df["admission_type"].value_counts(normalize=True) * 100
).round(2)

# Combine results into one table
admission_summary = pd.DataFrame({
    "Record Count": admission_counts,
    "Percentage (%)": admission_percentages
})

display(admission_summary)

                Record Count  Percentage (%)
admission_type
Elective               18473           33.61
Urgent                 18391           33.46
Emergency              18102           32.93

### Establish MySQL Database Connection

##### Install MySQL Database Connectors

In [26]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in C:\Users\LOQ\anaconda3\Lib\site-packages (26.7.0)

##### Import Essential Libraries

In [27]:
import mysql.connector
from getpass import getpass
from sqlalchemy import create_engine
from urllib.parse import quote_plus

##### Connect to MySQL Database

In [ ]:
password = quote_plus(getpass("Enter your MySQL password: "))

cnx = mysql.connector.connect(
    host="localhost",
    user="root",
    password=password,
    database="healthcare_analytics",
    port=3306
)

if cnx.is_connected():
    print("Connected to MySQL successfully!")

engine = create_engine(
    f"mysql+mysqlconnector://root:{password}@localhost:3306/healthcare_analytics"
)

##### Export DataFrame to MySQL

In [ ]:
table_name = "patient_data"
df.to_sql(table_name, engine, if_exists="replace", index=False)

##### Read back a sample

In [ ]:
sample_df = pd.read_sql("SELECT * FROM patient_data LIMIT 5;", engine)
display(sample_df)